### ISSUE TITLE
CefSharp Fork Under a Different name

### ISSUE THREAD

**Issue by amaitland** [Emposoft/MySurf-Engine#1]
Is there a particular reason you guys are forking `CefSharp` under a different name rather than forking the project and contributing code to the main project?

As a whole, your more than welcome to get involved with the development of `CefSharp`. Diverging efforts at this point seems somewhat pointless.

Is there something totally drastic your planning on doing going forward?

**Comment by AJDev77** [comment]
@amaitland I was planning on upgrading the version of CEF used to a newer version before you guys upgraded <code>CefSharp</code>... but now that you said it, I do agree that forking <code>CefSharp</code> and working together on the main project would be a lot better. Even though I am planning on upgrading the version of CEF used, am I still able to fork <code>CefSharp</code> and contribute to the main project? If I am able to contribute to the main project, I am still a student, so I might do some things wrong...

**Comment by amaitland** [comment]
@AJDev77 Which branch of `CEF` were you planning on using? We already have a branch for `2272` (`Chromium 41`) in the works. 

https://github.com/cefsharp/CefSharp/tree/cef/2272

> If I am able to contribute to the main project, I am still a student, so I might do some things wrong...

Most work doesn't directly happen on the `master` branch, typically you'd work in your own `fork`, when your happy, submit a `PR` and someone will review the code before merging. Don't worry about making a few mistakes, they should get picked up in the review process :+1: Once a couple of `PR's` have been successfully merged more than happy to talk about merge access :smile:

**Comment by javathunderman** [comment]
@amaitland If CEF is kept up to date with the latest versions of Chromium, I don't see why we can't use unchanged code as the MySurf engine- that would save quite a bit of work for us. We'd also like to focus on the development on the actual browser, however. @AJDev77 Am I misunderstanding anything here?

**Comment by amaitland** [comment]
> I don't see why we can't contribute code directly- that would save quite a bit of work for us.

Other than small changes we don't contribute code directly to `master`. Ideally all code is reviewed before it's merged. Standard practice for any open source project with multiple contributors.

A few other things come into play, like making sure the `API` is consistent and any breaking changes are thoroughly discussed.

For now I'd suggest you fork the main `CefSharp` repository, do all your work in a branch and periodically we can merge your changes back into `CefSharp`.

**Comment by javathunderman** [comment]
@AJDev77 With your OK, I'll delete this and fork the main CefSharp repo. Make a backup just in case something gets lost.

**Comment by AJDev77** [comment]
@amaitland Oh, I did not know that you had branch <code>2272</code>. Thanks!

@javathunderman Made the backup and put on network drive. Go ahead and delete this repo and fork <code>CefSharp</code> branch  <code>2272</code>.

**Comment by javathunderman** [comment]
@amaitland @AJDev77 Deleting and forking.
